# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jsearch.api.models.base_model_ import Model
from jsearch.api import util


class Balance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, balance: int=None, address: str=None):  # noqa: E501
        """Ballance - a model defined in Swagger

        :param ballance: The ballance of this Ballance.  # noqa: E501
        :type ballance: int
        :param address: The address of this Ballance.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'balance': int,
            'address': str
        }

        self.attribute_map = {
            'balance': 'ballance',
            'address': 'address'
        }

        self._balance = balance
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'Balance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ballance of this Ballance.  # noqa: E501
        :rtype: Ballance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> int:
        """Gets the ballance of this Ballance.


        :return: The ballance of this Ballance.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance: int):
        """Sets the ballance of this Ballance.


        :param ballance: The ballance of this Ballance.
        :type ballance: int
        """

        self._balance = balance

    @property
    def address(self) -> str:
        """Gets the address of this Ballance.


        :return: The address of this Ballance.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Ballance.


        :param address: The address of this Ballance.
        :type address: str
        """

        self._address = address
