# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jsearch.api.models.base_model_ import Model
from jsearch.api import util


class Reward(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, address: str=None, amount: int=None):  # noqa: E501
        """Reward - a model defined in Swagger

        :param address: The address of this Reward.  # noqa: E501
        :type address: str
        :param amount: The amount of this Reward.  # noqa: E501
        :type amount: int
        """
        self.swagger_types = {
            'address': str,
            'amount': int
        }

        self.attribute_map = {
            'address': 'address',
            'amount': 'amount'
        }

        self._address = address
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'Reward':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reward of this Reward.  # noqa: E501
        :rtype: Reward
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this Reward.


        :return: The address of this Reward.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Reward.


        :param address: The address of this Reward.
        :type address: str
        """

        self._address = address

    @property
    def amount(self) -> int:
        """Gets the amount of this Reward.


        :return: The amount of this Reward.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this Reward.


        :param amount: The amount of this Reward.
        :type amount: int
        """

        self._amount = amount
