# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jsearch.api.models.base_model_ import Model
from jsearch.api import util


class Web3CallResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: str=None, result: object=None):  # noqa: E501
        """Web3CallResponse - a model defined in Swagger

        :param status: The status of this Web3CallResponse.  # noqa: E501
        :type status: str
        :param result: The result of this Web3CallResponse.  # noqa: E501
        :type result: object
        """
        self.swagger_types = {
            'status': str,
            'result': object
        }

        self.attribute_map = {
            'status': 'status',
            'result': 'result'
        }

        self._status = status
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'Web3CallResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Web3CallResponse of this Web3CallResponse.  # noqa: E501
        :rtype: Web3CallResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this Web3CallResponse.


        :return: The status of this Web3CallResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Web3CallResponse.


        :param status: The status of this Web3CallResponse.
        :type status: str
        """

        self._status = status

    @property
    def result(self) -> object:
        """Gets the result of this Web3CallResponse.


        :return: The result of this Web3CallResponse.
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result: object):
        """Sets the result of this Web3CallResponse.


        :param result: The result of this Web3CallResponse.
        :type result: object
        """

        self._result = result
