# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jsearch.api.models.base_model_ import Model
from jsearch.api import util


class Web3Call(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, method: str=None, arguments: List[str]=None):  # noqa: E501
        """Web3Call - a model defined in Swagger

        :param method: The method of this Web3Call.  # noqa: E501
        :type method: str
        :param arguments: The arguments of this Web3Call.  # noqa: E501
        :type arguments: List[str]
        """
        self.swagger_types = {
            'method': str,
            'arguments': List[str]
        }

        self.attribute_map = {
            'method': 'method',
            'arguments': 'arguments'
        }

        self._method = method
        self._arguments = arguments

    @classmethod
    def from_dict(cls, dikt) -> 'Web3Call':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Web3Call of this Web3Call.  # noqa: E501
        :rtype: Web3Call
        """
        return util.deserialize_model(dikt, cls)

    @property
    def method(self) -> str:
        """Gets the method of this Web3Call.


        :return: The method of this Web3Call.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this Web3Call.


        :param method: The method of this Web3Call.
        :type method: str
        """

        self._method = method

    @property
    def arguments(self) -> List[str]:
        """Gets the arguments of this Web3Call.


        :return: The arguments of this Web3Call.
        :rtype: List[str]
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments: List[str]):
        """Sets the arguments of this Web3Call.


        :param arguments: The arguments of this Web3Call.
        :type arguments: List[str]
        """

        self._arguments = arguments
