class ErrorCode:
    """
    APi Error Codes
    """
    INVALID_VALUE = 'INVALID_VALUE'

    INVALID_LIMIT_VALUE = 'INVALID_LIMIT_VALUE'
    INVALID_OFFSET_VALUE = 'INVALID_OFFSET_VALUE'
    INVALID_ORDER_VALUE = 'INVALID_ORDER_VALUE'

    TOO_BIG_OFFSET_VALUE = 'TOO_BIG_OFFSET_VALUE'

    RESOURCE_NOT_FOUND = 'NOT_FOUND'
    BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND'

    TOO_MANY_ITEMS = 'TOO_MANY_ITEMS'

    PARAM_REQUIRED = 'PARAMETER_REQUIRED'
    UNKNOWN_VALUE = 'UNKNOWN_VALUE'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
