class ErrorCode:
    """
    APi Error Codes
    """
    INVALID_LIMIT_VALUE = 'INVALID_LIMIT_VALUE'
    INVALID_OFFSET_VALUE = 'INVALID_OFFSET_VALUE'
    INVALID_ORDER_VALUE = 'INVALID_ORDER_VALUE'

    BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND'
