version: '3.2'

services:
  tests:
    &tests
    depends_on:
      - test_main_db
      - test_raw_db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    image: jsearch/tests
    container_name: jsearch_tests
    entrypoint: /bin/sh
    command: -c "flake8 && pytest"
    environment:
      JSEARCH_MAIN_DB_TEST: postgres://postgres:postgres@test_main_db/jsearch-main
      JSEARCH_RAW_DB_TEST: postgres://postgres:postgres@test_raw_db/jsearch-raw
    env_file:
      - config/dev.env

  tests_shell:
    <<: *tests
    image: jsearch/tests
    entrypoint: /bin/bash
    command: ""
    volumes:
      - ./:/app


  test_raw_db:
    image: postgres:11.0-alpine
    container_name: jsearch_test_raw_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch-raw

  test_main_db:
    image: postgres:11.0-alpine
    container_name: jsearch_test_main_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch-main

