version: '3.2'

services:
  tests:
    &tests
    depends_on:
      - tests_main_db
      - tests_raw_db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    image: jsearch/tests
    container_name: jsearch_tests
    entrypoint: /bin/sh
    command: -c "flake8 && pytest"
    environment:
      JSEARCH_MAIN_DB_TEST: postgres://postgres:postgres@tests_main_db/jsearch_main
      JSEARCH_RAW_DB_TEST: postgres://postgres:postgres@tests_raw_db/jsearch_raw
    env_file:
      - config/dev.env

  tests_shell:
    <<: *tests
    image: jsearch/tests
    entrypoint: /bin/bash
    command: ""
    volumes:
      - ./:/app


  tests_raw_db:
    image: postgres:11.0-alpine
    container_name: jsearch_raw_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch_raw

  tests_main_db:
    image: postgres:11.0-alpine
    container_name: jsearch_main_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch_main

