version: '3.2'

services:
  dev:
    &dev
    depends_on:
      - test_main_db
      - test_raw_db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    image: jsearch/dev
    environment:
      JSEARCH_MAIN_DB: postgres://postgres:postgres@test_main_db/jsearch-main
      JSEARCH_RAW_DB: postgres://postgres:postgres@test_raw_db/jsearch-raw
    env_file:
      - config/dev.env

  dev_shell:
    <<: *dev
    image: jsearch/dev
    volumes:
      - ./:/app


  test_raw_db:
    image: postgres:11.0-alpine
    container_name: jsearch_test_raw_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch-raw

  test_main_db:
    image: postgres:11.0-alpine
    container_name: jsearch_test_main_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsearch-main

