"""empty message

Revision ID: 05380229cfad
Revises: df4321c571ac
Create Date: 2018-12-03 14:55:19.884108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05380229cfad'
down_revision = 'df4321c571ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('is_transfer_processed', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_logs_is_processed'), table_name='logs')
    op.create_index(
        op.f('ix_logs_is_token_transfer_multicolumn'),
        'logs',
        ['is_token_transfer', 'is_transfer_processed', 'block_number'],
        unique=False
    )
    op.create_index(
        op.f('ix_logs_is_transfer_processed_multicolumn'),
        'logs',
        ['is_processed', 'block_number'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_is_token_transfer_multicolumn'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_transfer_processed_multicolumn'), table_name='logs')
    op.create_index(op.f('ix_logs_is_processed'), 'logs', ['is_processed'], unique=False)
    op.drop_column('logs', 'is_transfer_processed')
    # ### end Alembic commands ###
