"""contract table

Revision ID: 0fcf7def677f
Revises: 824e5203bd9a
Create Date: 2018-04-09 16:14:30.492596

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fcf7def677f'
down_revision = '824e5203bd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('byte_code', sa.Text(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('abi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compiler_version', sa.String(), nullable=True),
    sa.Column('optimization_enabled', sa.Boolean(), nullable=True),
    sa.Column('optimization_runs', sa.Integer(), nullable=True),
    sa.Column('is_erc20_token', sa.Boolean(), nullable=True),
    sa.Column('token_name', sa.String(), nullable=True),
    sa.Column('token_symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
