"""token holders table

Revision ID: 1a59f9edd3f7
Revises: a53fe57acfd4
Create Date: 2018-06-21 16:21:55.167603

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '1a59f9edd3f7'
down_revision = 'a53fe57acfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_holders',
    sa.Column('account_address', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.CheckConstraint('balance >= 0', name='check_balance_positive'),
    sa.PrimaryKeyConstraint('account_address', 'token_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_holders')
    # ### end Alembic commands ###
    