"""empty message

Revision ID: 2cc4296ff59c
Revises: 9cdf71ca09d4
Create Date: 2018-05-16 15:11:05.036705

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '2cc4296ff59c'
down_revision = '9cdf71ca09d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('constructor_args', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('metadata_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_receipts_contract_address'), 'receipts', ['contract_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_contract_address'), table_name='receipts')
    op.drop_column('contracts', 'metadata_hash')
    op.drop_column('contracts', 'constructor_args')
    # ### end Alembic commands ###
