"""empty message

Revision ID: 4c6d4d4a850e
Revises: 608e6a6e0c55
Create Date: 2018-11-26 15:24:33.656147

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '4c6d4d4a850e'
down_revision = '608e6a6e0c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_token_transfer_from', table_name='transactions')
    op.drop_index('ix_transactions_token_transfer_to', table_name='transactions')
    op.drop_column('transactions', 'token_transfer_to')
    op.drop_column('transactions', 'is_token_transfer')
    op.drop_column('transactions', 'token_transfer_from')
    op.drop_column('transactions', 'token_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('token_transfer_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('is_token_transfer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('token_transfer_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_transactions_token_transfer_to', 'transactions', ['token_transfer_to'], unique=False)
    op.create_index('ix_transactions_token_transfer_from', 'transactions', ['token_transfer_from'], unique=False)
    # ### end Alembic commands ###
