"""float value of token transfer amountddd

Revision ID: 51db8b920e17
Revises: fc4b779adfcc
Create Date: 2018-11-08 13:55:31.628664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '51db8b920e17'
down_revision = 'fc4b779adfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'token_amount', type_=postgresql.NUMERIC(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'token_amount', type_=sa.BigInteger(), nullable=True)
    # ### end Alembic commands ###
