"""Add info about transfer to Log

Revision ID: 608e6a6e0c55
Revises: 51db8b920e17
Create Date: 2018-11-20 11:22:05.067377

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '608e6a6e0c55'
down_revision = '51db8b920e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('token_transfer_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('token_transfer_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('is_token_transfer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('token_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('is_processed', sa.Boolean(), autoincrement=False, default=False, nullable=True))
    op.create_index('ix_logs_token_transfer_to', 'logs', ['token_transfer_to'], unique=False)
    op.create_index('ix_logs_token_transfer_from', 'logs', ['token_transfer_from'], unique=False)
    op.create_index(op.f('ix_logs_block_number'), 'logs', ['block_number'], unique=False)
    op.create_index(op.f('ix_logs_is_processed'), 'logs', ['is_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_is_processed'), table_name='logs')
    op.drop_index(op.f('ix_logs_block_number'), table_name='logs')
    op.drop_index('ix_logs_token_transfer_from', table_name='logs')
    op.drop_index('ix_logs_token_transfer_to', table_name='logs')
    op.drop_column('logs', 'token_amount')
    op.drop_column('logs', 'is_token_transfer')
    op.drop_column('logs', 'token_transfer_to')
    op.drop_column('logs', 'token_transfer_from')
    op.drop_column('logs', 'is_processed')
    # ### end Alembic commands ###
