"""internal transactions parent_tx_hash fix type

Revision ID: 78d1cef4d630
Revises: 888414f0a46b
Create Date: 2018-07-12 18:05:05.553505

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '78d1cef4d630'
down_revision = '888414f0a46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internal_transactions', 'parent_tx_hash', type_=sa.String())
    op.alter_column('internal_transactions', 'value', type_=sa.NUMERIC(precision=32, scale=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internal_transactions', 'parent_tx_hash', type_=sa.Integer())
    op.alter_column('internal_transactions', 'value', type_=sa.String())
    # ### end Alembic commands ###
