"""Contracts and transfer tokens

Revision ID: 87463aa4f831
Revises: 0fcf7def677f
Create Date: 2018-04-21 09:32:34.532004

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87463aa4f831'
down_revision = '0fcf7def677f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('token_decimals', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('token_total_supply', sa.NUMERIC(precision=32, scale=0), nullable=True))
    op.add_column('transactions', sa.Column('contract_call_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('transactions', sa.Column('is_token_transfer', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('token_amount', sa.BigInteger(), nullable=True))
    op.add_column('logs', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('event_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'token_amount')
    op.drop_column('transactions', 'is_token_transfer')
    op.drop_column('transactions', 'contract_call_description')
    op.drop_column('contracts', 'token_total_supply')
    op.drop_column('contracts', 'token_decimals')
    op.drop_column('logs', 'event_type')
    op.drop_column('logs', 'event_args')
    # ### end Alembic commands ###
