"""internal transactions table update

Revision ID: 888414f0a46b
Revises: 1a59f9edd3f7
Create Date: 2018-07-12 18:01:11.929853

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '888414f0a46b'
down_revision = '1a59f9edd3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_transactions', sa.Column('payload', sa.String(), nullable=True))
    op.add_column('internal_transactions', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_transactions', 'status')
    op.drop_column('internal_transactions', 'payload')
    # ### end Alembic commands ###
