"""float value of token transfer amountddd

Revision ID: 88a65e8a2a2b
Revises: 51db8b920e17
Create Date: 2018-11-09 14:45:57.386613

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = '88a65e8a2a2b'
down_revision = '51db8b920e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('is_token_transfer', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('token_amount', sa.NUMERIC(), nullable=True))
    op.add_column('logs', sa.Column('token_transfer_from', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('token_transfer_to', sa.String(), nullable=True))
    op.create_index(op.f('ix_logs_token_transfer_from'), 'logs', ['token_transfer_from'], unique=False)
    op.create_index(op.f('ix_logs_token_transfer_to'), 'logs', ['token_transfer_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_token_transfer_to'), table_name='logs')
    op.drop_index(op.f('ix_logs_token_transfer_from'), table_name='logs')
    op.drop_column('logs', 'token_transfer_to')
    op.drop_column('logs', 'token_transfer_from')
    op.drop_column('logs', 'token_amount')
    op.drop_column('logs', 'is_token_transfer')
    # ### end Alembic commands ###
