"""Contracts scrape/update timestamp

Revision ID: 9cdf71ca09d4
Revises: 87463aa4f831
Create Date: 2018-05-03 16:14:32.103547

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cdf71ca09d4'
down_revision = '87463aa4f831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('grabbed_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'verified_at')
    op.drop_column('contracts', 'grabbed_at')
    # ### end Alembic commands ###
