"""token transfer to fom fields

Revision ID: a53fe57acfd4
Revises: 84f80746f265
Create Date: 2018-06-18 15:59:57.495308

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = 'a53fe57acfd4'
down_revision = '84f80746f265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token_transfer_from', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('token_transfer_to', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_token_transfer_from'), 'transactions', ['token_transfer_from'], unique=False)
    op.create_index(op.f('ix_transactions_token_transfer_to'), 'transactions', ['token_transfer_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_token_transfer_to'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_token_transfer_from'), table_name='transactions')
    op.drop_column('transactions', 'token_transfer_to')
    op.drop_column('transactions', 'token_transfer_from')
    # ### end Alembic commands ###
