"""Initial

Revision ID: d644f5ff507b
Revises: 
Create Date: 2018-12-05 15:36:06.343325

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd644f5ff507b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_base',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('last_known_balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('accounts_state',
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('nonce', tables.HexInteger(), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'address')
    )
    op.create_index(op.f('ix_accounts_state_block_number'), 'accounts_state', ['block_number'], unique=False)
    op.create_index(op.f('ix_accounts_state_is_forked'), 'accounts_state', ['is_forked'], unique=False)
    op.create_table('blocks',
    sa.Column('number', tables.HexInteger(), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('gas_limit', tables.HexBigInteger(), nullable=True),
    sa.Column('gas_used', tables.HexBigInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('miner', sa.String(), nullable=True),
    sa.Column('mix_hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('receipts_root', sa.String(), nullable=True),
    sa.Column('sha3_uncles', sa.String(), nullable=True),
    sa.Column('size', tables.HexInteger(), nullable=True),
    sa.Column('state_root', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('total_difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('transactions_root', sa.String(), nullable=True),
    sa.Column('is_sequence_sync', sa.Boolean(), nullable=True),
    sa.Column('static_reward', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('uncle_inclusion_reward', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('tx_fees', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_blocks_is_forked'), 'blocks', ['is_forked'], unique=False)
    op.create_index(op.f('ix_blocks_miner'), 'blocks', ['miner'], unique=False)
    op.create_index(op.f('ix_blocks_number'), 'blocks', ['number'], unique=False)
    op.create_table('internal_transactions',
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', tables.HexInteger(), nullable=False),
    sa.Column('parent_tx_hash', sa.String(), nullable=False),
    sa.Column('op', sa.String(), nullable=True),
    sa.Column('call_depth', tables.HexInteger(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('value', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('gas_limit', tables.HexBigInteger(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'parent_tx_hash', 'transaction_index')
    )
    op.create_index(op.f('ix_internal_transactions_block_number'), 'internal_transactions', ['block_number'], unique=False)
    op.create_index(op.f('ix_internal_transactions_is_forked'), 'internal_transactions', ['is_forked'], unique=False)
    op.create_table('logs',
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('log_index', tables.HexInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('transaction_index', tables.HexInteger(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_amount', sa.NUMERIC(), nullable=True),
    sa.Column('token_transfer_from', sa.String(), nullable=True),
    sa.Column('token_transfer_to', sa.String(), nullable=True),
    sa.Column('is_token_transfer', sa.Boolean(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_hash', 'block_hash', 'log_index')
    )
    op.create_index(op.f('ix_logs_block_hash'), 'logs', ['block_hash'], unique=False)
    op.create_index(op.f('ix_logs_block_number'), 'logs', ['block_number'], unique=False)
    op.create_index(op.f('ix_logs_is_forked'), 'logs', ['is_forked'], unique=False)
    op.create_index(op.f('ix_logs_is_processed'), 'logs', ['is_processed'], unique=False)
    op.create_index(op.f('ix_logs_token_transfer_from'), 'logs', ['token_transfer_from'], unique=False)
    op.create_index(op.f('ix_logs_token_transfer_to'), 'logs', ['token_transfer_to'], unique=False)
    op.create_table('mined_blocks',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('miner', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'miner')
    )
    op.create_table('mined_uncles',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('miner', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'miner')
    )
    op.create_table('receipts',
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('cumulative_gas_used', tables.HexInteger(), nullable=True),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('gas_used', tables.HexInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('transaction_index', tables.HexInteger(), nullable=False),
    sa.Column('status', tables.HexInteger(), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'transaction_index')
    )
    op.create_index(op.f('ix_receipts_block_number'), 'receipts', ['block_number'], unique=False)
    op.create_index(op.f('ix_receipts_contract_address'), 'receipts', ['contract_address'], unique=False)
    op.create_index(op.f('ix_receipts_is_forked'), 'receipts', ['is_forked'], unique=False)
    op.create_index(op.f('ix_receipts_transaction_hash'), 'receipts', ['transaction_hash'], unique=False)
    op.create_table('reorgs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('reinserted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_holders',
    sa.Column('account_address', sa.String(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.CheckConstraint('balance >= 0', name='check_balance_positive'),
    sa.PrimaryKeyConstraint('account_address', 'token_address')
    )
    op.create_index(op.f('ix_token_holders_balance'), 'token_holders', ['balance'], unique=False)
    op.create_table('transactions',
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('transaction_index', tables.HexInteger(), nullable=False),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('gas', sa.String(), nullable=True),
    sa.Column('gas_price', sa.String(), nullable=True),
    sa.Column('input', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('r', sa.String(), nullable=True),
    sa.Column('s', sa.String(), nullable=True),
    sa.Column('v', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('contract_call_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'transaction_index')
    )
    op.create_index(op.f('ix_transactions_block_hash'), 'transactions', ['block_hash'], unique=False)
    op.create_index(op.f('ix_transactions_block_number'), 'transactions', ['block_number'], unique=False)
    op.create_index(op.f('ix_transactions_from'), 'transactions', ['from'], unique=False)
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=False)
    op.create_index(op.f('ix_transactions_is_forked'), 'transactions', ['is_forked'], unique=False)
    op.create_index(op.f('ix_transactions_to'), 'transactions', ['to'], unique=False)
    op.create_table('uncles',
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('number', tables.HexInteger(), nullable=True),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('gas_limit', tables.HexBigInteger(), nullable=True),
    sa.Column('gas_used', tables.HexBigInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('miner', sa.String(), nullable=True),
    sa.Column('mix_hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('receipts_root', sa.String(), nullable=True),
    sa.Column('sha3_uncles', sa.String(), nullable=True),
    sa.Column('size', tables.HexInteger(), nullable=True),
    sa.Column('state_root', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('total_difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('transactions_root', sa.String(), nullable=True),
    sa.Column('reward', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('is_forked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'hash')
    )
    op.create_index(op.f('ix_uncles_block_number'), 'uncles', ['block_number'], unique=False)
    op.create_index(op.f('ix_uncles_hash'), 'uncles', ['hash'], unique=False)
    op.create_index(op.f('ix_uncles_is_forked'), 'uncles', ['is_forked'], unique=False)
    op.create_index(op.f('ix_uncles_number'), 'uncles', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uncles_number'), table_name='uncles')
    op.drop_index(op.f('ix_uncles_is_forked'), table_name='uncles')
    op.drop_index(op.f('ix_uncles_hash'), table_name='uncles')
    op.drop_index(op.f('ix_uncles_block_number'), table_name='uncles')
    op.drop_table('uncles')
    op.drop_index(op.f('ix_transactions_to'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_forked'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_hash'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_token_holders_balance'), table_name='token_holders')
    op.drop_table('token_holders')
    op.drop_table('reorgs')
    op.drop_index(op.f('ix_receipts_transaction_hash'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_is_forked'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_contract_address'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_block_number'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_table('mined_uncles')
    op.drop_table('mined_blocks')
    op.drop_index(op.f('ix_logs_token_transfer_to'), table_name='logs')
    op.drop_index(op.f('ix_logs_token_transfer_from'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_processed'), table_name='logs')
    op.drop_index(op.f('ix_logs_is_forked'), table_name='logs')
    op.drop_index(op.f('ix_logs_block_number'), table_name='logs')
    op.drop_index(op.f('ix_logs_block_hash'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_internal_transactions_is_forked'), table_name='internal_transactions')
    op.drop_index(op.f('ix_internal_transactions_block_number'), table_name='internal_transactions')
    op.drop_table('internal_transactions')
    op.drop_index(op.f('ix_blocks_number'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_miner'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_is_forked'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_accounts_state_is_forked'), table_name='accounts_state')
    op.drop_index(op.f('ix_accounts_state_block_number'), table_name='accounts_state')
    op.drop_table('accounts_state')
    op.drop_table('accounts_base')
    # ### end Alembic commands ###
