"""split-accounts-data

Revision ID: df4321c571ac
Revises: 51db8b920e17
Create Date: 2018-11-23 14:34:59.509714

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables


# revision identifiers, used by Alembic.
revision = 'df4321c571ac'
down_revision = '608e6a6e0c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_base',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('last_known_balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('accounts_state',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('nonce', tables.HexInteger(), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'address')
    )
    op.create_index(op.f('ix_accounts_state_block_hash'), 'accounts_state', ['block_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_state_block_hash'), table_name='accounts_state')
    op.drop_table('accounts_state')
    op.drop_table('accounts_base')
    # ### end Alembic commands ###
