"""Initial

Revision ID: f150f7b5fcae
Revises: 
Create Date: 2018-03-25 18:38:04.297126

"""
from alembic import op
import sqlalchemy as sa
from jsearch.common import tables
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f150f7b5fcae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('nonce', tables.HexInteger(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=32, scale=0), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('storage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'address')
    )
    op.create_table('blocks',
    sa.Column('number', tables.HexInteger(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('gas_limit', tables.HexInteger(), nullable=True),
    sa.Column('gas_used', tables.HexInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('miner', sa.String(), nullable=True),
    sa.Column('mix_hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('receipts_root', sa.String(), nullable=True),
    sa.Column('sha3_uncles', sa.String(), nullable=True),
    sa.Column('size', tables.HexInteger(), nullable=True),
    sa.Column('state_root', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('total_difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('transactions_root', sa.String(), nullable=True),
    sa.Column('is_sequence_sync', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('internal_transactions',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('parent_tx_hash', tables.HexInteger(), nullable=False),
    sa.Column('op', sa.String(), nullable=True),
    sa.Column('depth', tables.HexInteger(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('gas_limit', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'parent_tx_hash', 'to')
    )
    op.create_table('logs',
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('log_index', tables.HexInteger(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('transaction_index', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_hash', 'log_index')
    )
    op.create_table('mined_blocks',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('miner', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'miner')
    )
    op.create_table('mined_uncles',
    sa.Column('block_number', tables.HexInteger(), nullable=False),
    sa.Column('miner', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('block_number', 'miner')
    )
    op.create_table('receipts',
    sa.Column('transaction_hash', sa.String(), nullable=False),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('cumulative_gas_used', tables.HexInteger(), nullable=True),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('gas_used', tables.HexInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('root', sa.String(), nullable=True),
    sa.Column('transaction_index', tables.HexInteger(), nullable=True),
    sa.Column('status', tables.HexInteger(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_hash')
    )
    op.create_table('transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('transaction_index', tables.HexInteger(), nullable=True),
    sa.Column('from', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.Column('gas', sa.String(), nullable=True),
    sa.Column('gas_price', sa.String(), nullable=True),
    sa.Column('input', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('r', sa.String(), nullable=True),
    sa.Column('s', sa.String(), nullable=True),
    sa.Column('v', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('uncles',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('number', tables.HexInteger(), nullable=False),
    sa.Column('block_number', tables.HexInteger(), nullable=True),
    sa.Column('block_hash', sa.String(), nullable=True),
    sa.Column('parent_hash', sa.String(), nullable=True),
    sa.Column('difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('gas_limit', tables.HexInteger(), nullable=True),
    sa.Column('gas_used', tables.HexInteger(), nullable=True),
    sa.Column('logs_bloom', sa.String(), nullable=True),
    sa.Column('miner', sa.String(), nullable=True),
    sa.Column('mix_hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('receipts_root', sa.String(), nullable=True),
    sa.Column('sha3_uncles', sa.String(), nullable=True),
    sa.Column('size', tables.HexInteger(), nullable=True),
    sa.Column('state_root', sa.String(), nullable=True),
    sa.Column('timestamp', tables.HexInteger(), nullable=True),
    sa.Column('total_difficulty', tables.HexBigInteger(), nullable=True),
    sa.Column('transactions_root', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash', 'number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uncles')
    op.drop_table('transactions')
    op.drop_table('receipts')
    op.drop_table('mined_uncles')
    op.drop_table('mined_blocks')
    op.drop_table('logs')
    op.drop_table('internal_transactions')
    op.drop_table('blocks')
    op.drop_table('accounts')
    # ### end Alembic commands ###
